version: '3'
services:
  db:
    image: mysql/mysql-server:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_DATABASE=matel"
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build: ./api
    image: matel-api
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - api:/main
    depends_on:
      - db
    links:
      - "db:database"
    extra_hosts:
     - "host.docker.internal:host-gateway"
  web:
    build: ./web
    ports:
      - "3000:3000"
    image: matel-web
    restart: always
    volumes:
      - web:/var/www/dockerize-nuxt/nuxt-app
    command: "npm run start"
    extra_hosts:
     - "host.docker.internal:host-gateway"
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    links:
      - "api:api"
      - "web:web"
    environment:
      - DOMAIN=taurusaplikasi.com
    command: ["/bin/bash", "-c", "export DOMAIN && envsubst '$$DOMAIN' < /etc/nginx/nginx.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"]
  crontab:
    build: ./crontab
    restart: always

volumes:
  api:
  web:
  db:
    driver: local