version: '3'
services:
  db:
    image: mysql/mysql-server:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_DATABASE=matel"
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build: .
    image: matel-api
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - api:/main
    depends_on:
      - db
    links:
      - "db:database"
    extra_hosts:
     - "host.docker.internal:host-gateway"
  nginx:
    build: nginx:latest
    image: matel-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    links:
      - "api:api"
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    links:
      - "nginx:nginx"

volumes:
  nginx:
  api:
  db:
    driver: local