version: '3'
services:
  db:
    image: mysql/mysql-server:latest
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_DATABASE=matel"
  web:
    build: .
    ports:
      # 80 on the host, 8080 on the guest. Websever listens on 8080
      - "80:9000" # http
      - "443:443" # https
    volumes:
      - ".:/main"
    depends_on:
      - db
    links:
      - "db:database"