version: '3'
services:
  db:
    image: mysql/mysql-server:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_DATABASE=matel"
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  nginx:
    build: ./nginx
    image: matel-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - api:/main
    depends_on:
      - api
    links:
      - "api:api"
    extra_hosts:
     - "host.docker.internal:host-gateway"
  api:
    build: .
    image: matel-api
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - api:/main
    depends_on:
      - db
    links:
      - "db:database"
    extra_hosts:
     - "host.docker.internal:host-gateway"

volumes:
  nginx:
  api:
  db:
    driver: local