version: '3'
services:
  db:
    image: mysql/mysql-server:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_DATABASE=matel"
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  api:
    build: .
    image: matel-api
    restart: always
    volumes:
      - ".:/main"
    depends_on:
      - db
    links:
      - "db:database"
    network_mode: "host"

volumes:
  db:
    driver: local